version: 2.1

orbs:
  snyk: snyk/snyk@1.1.2
  styra-orb: styra/cli@0.0.7

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!!"
  styra-policy-check:
    executor: cli
    steps:
      - checkout
      - policy-check:
          api_token: STYRA_TOKEN
          tenant: STYRA_TENANT
  init:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: "Terraform Init"
          command: |
            ls -all
            cat .terraformrc
            terraform login
            terraform init

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
  check-workflow:
    jobs:
      - snyk/scan-iac
      - styra-orb/styra-policy-check
  terraform-workflow:
    jobs:
      - init
