version: 2.1

orbs:
  snyk: snyk/snyk@1.1.2
  styra-orb: styra/cli@0.0.7
  terraform: circleci/terraform@3.0.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!!"
  styra-policy-check:
      executor: cli
      steps:
        - checkout
        - policy-check:
            api_token: STYRA_TOKEN
            tenant: STYRA_TENANT
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: .
      - terraform/validate:
          path: .
      - terraform/fmt:
          path: .
      - terraform/plan:
          path: .
      - terraform/apply:
          path: .
      - terraform/destroy:
          path: .
    working_directory: ~/src

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
  check-workflow:
    jobs:
      - snyk/scan-iac
      - styra-orb/styra-policy-check
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle
