version: 2.1

orbs:
  snyk: snyk/snyk@1.1.2
  styra-orb: styra/cli@0.0.7

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!!"
  styra-policy-check:
    executor: cli
    steps:
      - checkout
      - policy-check:
          api_token: STYRA_TOKEN
          tenant: STYRA_TENANT
  plan:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            export TF_CLI_CONFIG_FILE=./.terraformrc
            terraform init
            terraform plan -out tfplan-$CIRCLE_SHA1
      - persist_to_workspace:
          root: .
          paths:
            - .
  apply:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform apply
          command: |
            export TF_CLI_CONFIG_FILE=./.terraformrc
            terraform init
            terraform apply -auto-approve "tfplan-CIRCLE_SHA1"
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
  check-workflow:
    jobs:
      - snyk/scan-iac
      - styra-orb/styra-policy-check
  terraform-workflow:
    jobs:
      - plan
      - apply:
          requires:
            - plan
