version: 2.1

orbs:
  snyk: snyk/snyk@1.1.2
  styra-orb: styra/cli@0.0.7
  terraform: circleci/terraform@3.0.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!!"
  styra-policy-check:
      executor: cli
      steps:
        - checkout
        - policy-check:
            api_token: STYRA_TOKEN
            tenant: STYRA_TENANT

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
  check-workflow:
    jobs:
      - snyk/scan-iac
      - styra-orb/styra-policy-check
  terraform-workflow:
    jobs:
      - terraform/fmt:
          checkout: true
          context: terraform
      - terraform/validate:
          checkout: true
          context: terraform
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - terraform/validate
      - terraform/apply:
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: master
          requires:
            - terraform/plan
